### ISSUE TITLE
Installation script breaks... all the things, really

### ISSUE THREAD

**Issue by bbriggs** [naworkcaj/bdvl#3] opened 2020-03-01 03:07 UTC
I'd love to help debug this and it seems similar to #2

Using the switches one at a time leaves errors with things missing, such as this:
```
 [+] Finished installing dependencies
 [..] Building & writing C char arrays for the lib headers
 [..] Writing background variables
 [..] Getting hidden port ranges
 [..] Overwriting variable placeholders with new settings

 [..] BD_UNAME = nivcylb
 [..] BD_PWD = fdhraei
 [..] MAGIC_GID = 5228
 [..] ACCEPT_PORT = 446
 [..] PAM_PORT = 452

gcc: error: libmelpam.so.inc/bedevil.c: No such file or directory
```

When using the full install (`-i`) it actually breaks bash pretty impressively.

```
 [+] Starting full installation!

 [!] Patch dynamic linker libs? [Y/n]: y [..] Patching dynamic linker libraries
sed: -e expression #1, char 62: unterminated `s' command
sed: -e expression #1, char 62: unterminated `s' command
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
etc/patch_libdl.sh: line 40: /usr/bin/strings: Input/output error
 [+] New ld.so.preload location: /lib/python2.7/hotshot.1RijwBIty4E2U8n5D

 [!] Install potential dependencies? [Y/n]: y./bedevil.sh: etc/install_deps.sh: /bin/bash: bad interpreter: Input/output error

./bedevil.sh: line 52: /usr/bin/cp: Input/output error
 [!] Couldn't copy module directory
-bash: /usr/bin/grep: Input/output error
-bash: /usr/bin/grep: Input/output error
-bash: /usr/bin/wc: Input/output error
-bash: ((: r =  : syntax error: operand expected (error token is "=  ")
-bash: /usr/bin/wc: Input/output error
-bash: ((: s =  : syntax error: operand expected (error token is "=  ")
[root@kali:/mnt/ccdc/bdvl] 10s #
-bash: /usr/bin/grep: Input/output error
-bash: /usr/bin/grep: Input/output error
-bash: /usr/bin/wc: Input/output error
-bash: ((: r =  : syntax error: operand expected (error token is "=  ")
-bash: /usr/bin/wc: Input/output error
-bash: ((: s =  : syntax error: operand expected (error token is "=  ")
[root@kali:/mnt/ccdc/bdvl] #
```

**Comment by naworkcaj** [comment] 2020-03-26 20:06
Thanks for submitting this. :fireworks:  
I'm a little confused when you're saying 'using the switches one at a time'. Are you running each part of the main script at separate times?
In the second block of output, it looks as if you've manually installed the rootkit's library yourself then tried running the installation again... I could be wrong, but that spaghetti of IO errors is what tends to happen after installation has finished and not during.

**Comment by bbriggs** [comment] 2020-04-06 15:43
I'll work on doing some fault isolation but basically the "install all the things" switch leaves me with a broken terminal, so when I go through and run `bdvl` with the switches/options in the order they are applied in the installation script (to simulate the `-i` option), I get the first error I pasted.

**Comment by naworkcaj** [comment] 2020-04-14 01:10
My priorities as of the most recent commits have been making sure the box is actually usable (lol) for regular users, and that the PAM backdoor works as intended.
I've made a note in the README of how you can simulate an installation on the box without actually setting anything in stone. (until you want to??)
Afaik, installation won't totally brick the box now. + the PAM backdoor does actually work now. Now that the box is usable upon installation, I'm going to work more on debloating (for lack of a better word) the rootkit.
If you could, whenever possible, have a look at the most recent commit and see if you're still having similar problems to the same degree as you previously were.

**Comment by naworkcaj** [comment] 2020-04-17 07:09
As far as I'm aware, the problems that had existed when this issue was posted have been resolved.
Therefore, I am going to close this issue for the time being. If similar problems present themselves, don't hesitate to open a new issue.

**Closed by naworkcaj** 2020-04-17 07:09 UTC

**Comment by hackendltd** [comment] 2020-04-17 13:51
etc/patch_libdl.sh: line 69: random: command not found
