### ISSUE TITLE
Couldn't strip libqweryr.so.x86_64, exiting

### ISSUE THREAD

**Issue by hackendltd** [naworkcaj/bdvl#11] opened 2020-04-18 08:46 UTC
centos7 does not have xxd installed by default
---yum provides xxd
---yum install vim-common-7.4.629-6.el7.x86_64 -y

 [..] Beginning toggle configuration...
 [!] USE_PAM_BD = false. Switch? [Y/n]: y
 [!] USE_ACCEPT_BD = false. Switch? [Y/n]: y
 [!] ACCEPT_USE_SSL = false. Switch? [Y/n]: y
 [!] LOG_LOCAL_AUTH = false. Switch? [Y/n]: y
 [!] FILE_STEAL = false. Switch? [Y/n]: y
 [+] Starting full installation!

 [!] Make sure any essential dependencies are present.
 [!] You can install them with './bedevil.sh -D'
 [!] Patch dynamic linker libs? [Y/n]: y [..] Patching dynamic linker libraries, please wait...
 [+] Finished patching dynamic linker

 [+] Beginning configuration...

 [..] Getting hooks
 [..] Finding header paths
 [..] Preparing your settings

 [+] These are your defined/generated settings:

 [..] BD_UNAME = dkqpbo
 [..] BD_PWD = xxodrl
 [..] MAGIC_GID = 616
 [..] BD_VAR = PAWUMXDOT
 [..] INSTALL_DIR = /usr/share/localezo
 [..] BDVLSO = libqweryr.so
 [..] SOPATH = /usr/share/localezo/libqweryr.so.$PLATFORM
 [..] LDSO_PRELOAD = /usr/lib/kdumpod.N
 [..] HIDEPORTS = /lib/firmware/mediatekol
 [..] ACCEPT_PORT = 2919
 [..] PAM_PORT = 7522
 [..] INTEREST_DIR = /usr/lib64/tlszf

 [..] Overwriting old variable placeholders
 [!] Couldn't strip libqweryr.so.x86_64, exiting
[root@localhost bdvl]# id
uid=0(root) gid=0(root) groups=0(root)

**Comment by naworkcaj** [comment] 2020-04-18 16:36
`etc/install_deps.sh` already installs the vim-common package when used. There is a notice message before starting installation that you should make sure all required dependencies are present before continuing.

Now, if `patch_libdl.sh` can't find xxd, it will output a suitable error message and make a point of using `install_deps.sh` to install any necessary packages before exiting.
`bedevil.sh` will now do the same check before asking if you want to patch the dynamic linker, and will output an appropriate message if it can't find xxd.
I'll push this commit soon so that I can get this fixed. Appreciated.

**Comment by naworkcaj** [comment] 2020-04-18 21:20
100% certain this is caused by failure to install dependencies. Closing this issue.

**Closed by naworkcaj** 2020-04-18 21:20 UTC

**Comment by octayn** [comment] 2020-07-16 02:18
Having the same issue:


Deps are installed:
```
root@debian-s-1vcpu-1gb-nyc3-01:~/bdvl# etc/install_deps.sh
 [..] Installing dependencies
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://mirrors.digitalocean.com/debian stretch InRelease
Hit:3 http://mirrors.digitalocean.com/debian stretch-updates InRelease
Hit:4 http://mirrors.digitalocean.com/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc-multilib is already the newest version (4:6.3.0-4).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.3).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpcap-dev is already the newest version (1.8.1-3).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpcap0.8-dev is already the newest version (1.8.1-3).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
 [+] Finished installing dependencies
```

With -v flag:
```
[+] Starting full installation!

 [!] All essential dependencies must be present!
 [!] You can install them with './bedevil.sh -D' before continuing

 [!] Patch dynamic linker libs? [Y/n]: n

 [+] Beginning configuration...

 [..] Getting hooks
 [..] Finding header paths

 [..] Preparing your settings

 [..] This is the configuration of this bdvl.
 [..] BD_UNAME = mzykp
 [..] BD_PWD = 9lVLAnKh
 [..] MAGIC_GID = 718486
 [..] BD_VAR = VDEZEDMKQ
 [..] INSTALL_DIR = /lib/ifupdownznu
 [..] BDVLSO = libifupdownznu.so
 [..] SOPATH = /lib/ifupdownznu/libifupdownznu.so.$PLATFORM
 [..] LDSO_PRELOAD = /etc/ld.so.preload
 [..] SSH_LOGS = /usr/includeozl
 [..] INTEREST_DIR = /lib/firmwareixt
 [..] HIDEPORTS = /usr/gamesjc
 [..] GID_PATH = /lib/initmkg
 [..] GIDTIME_PATH = /usr/sbinmzt
 [..] SSHD_CONFIG = /etc/ssh/sshd_config

 [..] Overwriting old variable placeholders
strip: 'libifupdownznu.so.x86_64': No such file
 [!] Couldn't strip libifupdownznu.so.x86_64, exiting
```
