### ISSUE TITLE
centos 2.6.32-573 x86-64 crashes

### ISSUE THREAD

**Issue by hackendltd** [naworkcaj/bdvl#8] opened 2020-04-04 07:50 UTC
root@localhost bdvl-master]# ./bedevil.sh -ti

   /$$                     /$$                   /$$/$$
  | $$                    | $$                  |__| $$
  | $$$$$$$  /$$$$$$  /$$$$$$$ /$$$$$$ /$$    /$$/$| $$
  | $$__  $$/$$__  $$/$$__  $$/$$__  $|  $$  /$$| $| $$
  | $$  \ $| $$$$$$$| $$  | $| $$$$$$$$\  $$/$$/| $| $$
  | $$  | $| $$_____| $$  | $| $$_____/ \  $$$/ | $| $$
  | $$$$$$$|  $$$$$$|  $$$$$$|  $$$$$$$  \  $/  | $| $$
  |_______/ \_______/\_______/\_______/   \_/   |__|__/
                                                     
               LD_PRELOAD Linux rootkit
               
./etc/util.sh: line 87: ${#a}-1: substring expression < 0
 [..] Beginning toggle configuration...
 [!] USE_ACCEPT_BD = false. Switch? [Y/n]: y
 [!] USE_PAM_BD = false. Switch? [Y/n]: y
 [!] LOG_LOCAL_AUTH = false. Switch? [Y/n]: y
 [!] LOG_SSH = false. Switch? [Y/n]: y
 [!] FILE_STEAL = false. Switch? [Y/n]: y
 [!] ACCEPT_USE_SSL = false. Switch? [Y/n]: y
 [+] Starting full installation!

 [!] Patch dynamic linker libs? [Y/n]: y
 [..] Patching dynamic linker libraries, please wait...
 [+] Finished patching dynamic linker
 [!] Install potential dependencies? [Y/n]: y
 [..] Installing dependencies
Package 14:libpcap-1.4.0-4.20130826git2dbcaa1.el6.x86_64 already installed and latest version
Package 14:libpcap-devel-1.4.0-4.20130826git2dbcaa1.el6.x86_64 already installed and latest version
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for libgcc which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of libgcc of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude libgcc.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of libgcc installed, but
            yum can only see an upgrade for one of those arcitectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of libgcc installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: libgcc-4.4.7-23.el6.i686 != libgcc-4.4.7-16.el6.x86_64
 [+] Finished installing dependencies
 [..] Building & writing C char arrays for the lib headers
 [..] Writing background variables
 [..] Getting hidden ports
 [..] Getting variable placeholders and their new values

 [..] BD_UNAME = lumzgyps
 [..] BD_PWD = nwvydgev
 [..] MAGIC_GID = 1581

 [..] Overwriting old variable placeholders with new settings
 [+] Rootkit compiled. (lib.so.x86_64 - 53K)
 [..] Installing to /usr/include/asm-generic/.32211
 [..] Writing $SOPATH to /lib/modules/2.6.3
 [+] Installation finished
 [..] Cleaning up local mess

./bedevil.sh: line 93: export: `=1': not a valid identifier
 [..] Hiding rootkit files
 [+] Installation complete!

**Comment by hackendltd** [comment] 2020-04-04 07:51
The accept backdoor cannot be connected, and the system crashes after restarting

**Comment by naworkcaj** [comment] 2020-04-14 00:57
Thanks for both of these posts. I've closed the most recent one as both of these don't tell me anything I don't already know, and I've committed a fair amount of updates to the rootkit itself and its setup scripts.
I've been putting all of my recent efforts into making sure the box is actually usable upon installation... That and the PAM backdoor works as intended. For the time being, until everything else works optimally, I'm not really focusing on the accept backdoor.
If you can, please try with the most recent commit and get back to me whenever possible.

**Comment by hackendltd** [comment] 2020-04-14 05:33
> Thanks for both of these posts. I've closed the most recent one as both of these don't tell me anything I don't already know, and I've committed a fair amount of updates to the rootkit itself and its setup scripts.
> I've been putting all of my recent efforts into making sure the box is actually usable upon installation... That and the PAM backdoor works as intended. For the time being, until everything else works optimally, I'm not really focusing on the accept backdoor.
> If you can, please try with the most recent commit and get back to me whenever possible.

Thanks, I used for actual testing.

**Closed** 2020-04-14 17:29 UTC
